### ISSUE TITLE
Course cannot be displayed 

### ISSUE THREAD

**Issue by gingerjh** [openedx/openedx-demo-course#2]
How to deal with import problems (we import the course to 100% but nothing shows up
in course outline, files are correct and have content)?

2013/10/23
Tried again and the course was imported successfully. However, the course cannot be show properly in LMS and there are errors in some pages in CMS.

**Comment by jswope00** [comment]
This issue is 10 years old now :) 

The original demoX course has been replaced and new course has been tested to import into all versions of Open edX LMS.
