### ISSUE TITLE
Demonstration Course not exporting in Open edX Olive Demo Server

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-demo-course#39]
### Description
The demonstration course fails while exporting due to missing transcripts. This happened in the Nutmeg release demo installation & now in the Olive demo.

For a more detailed description, please refer to: https://github.com/openedx/build-test-release-wg/issues/207.

**Comment by sambapete** [comment]
If you import the official demo course from the tarball available on https://github.com/openedx/openedx-demo-course you will not encounter this problem. I believe we are using a defective version of the demo course. Or there is a problem in the way the course is being imported through the Tutor installation process used to create the Olive Demo Server.

https://github.com/openedx/edx-demo-course/releases/download/v1.1/edx_demo_course_1_1.tar.gz

If you check the contents of the course that currently has problems, you will notice that the contents is different than the one coming with the tarball.

**Comment by mariajgrimaldi** [comment]
The transcripts are not imported when importing the course using the tutor command, so that's the error raised. This also fails in my local environment, not sure if it has to do with the course release or the command itself.

Also, the tarball available is an old release, and that's probably why it's working when importing it directly 🤔

**Comment by jswope00** [comment]
This issue applies to the old DemoX course, which has been replaced at this point by a newer version and also tested for export/import including tutor import. I will close this issue.
